/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ProxyStorageInterface extends utils.Interface {
  functions: {
    "proxyOwner()": FunctionFragment;
    "currentContract()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "proxyOwner" | "currentContract"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "proxyOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentContract",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "proxyOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentContract",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ProxyStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ProxyStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    proxyOwner(overrides?: CallOverrides): Promise<[string]>;

    currentContract(overrides?: CallOverrides): Promise<[string]>;
  };

  proxyOwner(overrides?: CallOverrides): Promise<string>;

  currentContract(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    proxyOwner(overrides?: CallOverrides): Promise<string>;

    currentContract(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    proxyOwner(overrides?: CallOverrides): Promise<BigNumber>;

    currentContract(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    proxyOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
