/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  Migration,
  MigrationInterface,
} from "../../../../../contracts/examples/libraries/Migrate_1_3_0_to_1_2_0.sol/Migration";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "targetSingleton",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "singleton",
        type: "address",
      },
    ],
    name: "ChangedMasterCopy",
    type: "event",
  },
  {
    inputs: [],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "migrationSingleton",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "safe120Singleton",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60c060405234801561001057600080fd5b5060405161036438038061036483398101604081905261002f916100b1565b6001600160a01b0381166100945760405162461bcd60e51b815260206004820152602260248201527f496e76616c69642073696e676c65746f6e20616464726573732070726f766964604482015261195960f21b606482015260840160405180910390fd5b6001600160601b0319606091821b1660a05230901b6080526100e1565b6000602082840312156100c357600080fd5b81516001600160a01b03811681146100da57600080fd5b9392505050565b60805160601c60a05160601c61024d61011760003960008181608e0152610160015260008181604b015260c5015261024d6000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80632e7731851461004657806389f54308146100895780638fd3ab80146100b0575b600080fd5b61006d7f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f35b61006d7f000000000000000000000000000000000000000000000000000000000000000081565b6100b86100ba565b005b306001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001614156101505760405162461bcd60e51b815260206004820152603060248201527f4d6967726174696f6e2073686f756c64206f6e6c792062652063616c6c65642060448201526f1d9a584819195b1959d85d1958d85b1b60821b606482015260840160405180910390fd5b600080546001600160a01b0319167f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316179055604080517f035aff83d86937d35b32e04f0ddc6ff469290eef2f1b692d8a815c89404d47496020820152309181019190915260600160408051808303601f190181529082905280516020918201206006556000546001600160a01b031682527f75e41bc35ff1bf14d81d1d2f649c0084a0f974f9289c803ec9898eeec4c8d0b8910160405180910390a156fea2646970667358221220dfe61467549a685d8ee47e608e25bb5f6b2aa4737f3b84ffac547cc95e87cd3164736f6c63430008070033";

type MigrationConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MigrationConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Migration__factory extends ContractFactory {
  constructor(...args: MigrationConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    targetSingleton: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Migration> {
    return super.deploy(targetSingleton, overrides || {}) as Promise<Migration>;
  }
  override getDeployTransaction(
    targetSingleton: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(targetSingleton, overrides || {});
  }
  override attach(address: string): Migration {
    return super.attach(address) as Migration;
  }
  override connect(signer: Signer): Migration__factory {
    return super.connect(signer) as Migration__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MigrationInterface {
    return new utils.Interface(_abi) as MigrationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Migration {
    return new Contract(address, _abi, signerOrProvider) as Migration;
  }
}
