/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as estateRegistrySol from "./EstateRegistry.sol";
export type { estateRegistrySol };
import type * as landProxySol from "./LANDProxy.sol";
export type { landProxySol };
import type * as landRegistrySol from "./LANDRegistry.sol";
export type { landRegistrySol };
