/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testSmartContractWalletSol from "./TestSmartContractWallet.sol";
export type { testSmartContractWalletSol };
import type * as testUsdtSol from "./TestUSDT.sol";
export type { testUsdtSol };
export type { TestAuthenticatedProxy } from "./TestAuthenticatedProxy";
export type { TestERC1155 } from "./TestERC1155";
export type { TestERC1271 } from "./TestERC1271";
export type { TestERC20 } from "./TestERC20";
export type { TestERC721 } from "./TestERC721";
