/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDecentralandFacet } from "./IDecentralandFacet";
export type { IDecentralandRegistry } from "./IDecentralandRegistry";
