/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRentable,
  IRentableInterface,
} from "../../../contracts/interfaces/IRentable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_assetId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_rentId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_referrer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_fee",
        type: "uint256",
      },
    ],
    name: "AccrueReferralFee",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_assetId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_rentId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_renter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_start",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_end",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_rent",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_protocolFee",
        type: "uint256",
      },
    ],
    name: "Rent",
    type: "event",
  },
] as const;

export class IRentable__factory {
  static readonly abi = _abi;
  static createInterface(): IRentableInterface {
    return new utils.Interface(_abi) as IRentableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRentable {
    return new Contract(address, _abi, signerOrProvider) as IRentable;
  }
}
