/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EstateRegistryMock__factory } from "./EstateRegistryMock__factory";
export { LANDProxyMock__factory } from "./LANDProxyMock__factory";
export { LANDRegistryMock__factory } from "./LANDRegistryMock__factory";
