/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EstateRegistryMock } from "./EstateRegistryMock";
export type { LANDProxyMock } from "./LANDProxyMock";
export type { LANDRegistryMock } from "./LANDRegistryMock";
