/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as decentraland from "./decentraland";
export type { decentraland };
import type * as token from "./token";
export type { token };
export type { Test1Facet } from "./Test1Facet";
export type { Test2Facet } from "./Test2Facet";
